# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        cd src/Admin.Template
        dotnet restore
    - name: Build
      run: |
        cd src/Admin.Template/Server
        dotnet build --configuration Release --no-restore

    - name: Build .NET project
      run: dotnet publish -c Release -o root --no-self-contained

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: root
        path: root

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: root

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'

        git clone https://github.com/${{ github.repository }}.git gh-pages
        cd gh-pages
        git checkout gh-pages

        # Remove existing content (use with caution)
        # rm -rf *

        # Copy the artifacts to the repository
        cp -R ../root/* .

        git add .
        git commit -m 'Update GitHub Pages'
        git push
